### PR TITLE
RadioButton support multiple groups

### PR DESCRIPTION
**Pull request by pihao**
:smile:

### CODE REVIEW

**Comment by pihao** [comment]
Oh! It‘s seven years ago! ActionScript 3.0 has become history. Thanks to minimalcomps!

**Comment by ROBERT-MCDOWELL** [comment]
it's never too late. coding is like wine, more it's old better it is

**Comment by bit101** [comment]
There is now https://www.minimalcomps2.com/ if you weren't aware. :)

**Comment by pihao** [comment]
yes, I subscribe your blog for all these years case of minimalcomps.

**Comment by pardoman** [comment]
I remember using Minimal components A LOT back in the (AS3) day(s). Good memories; glad to see there's a v2 for JS :)

**Comment by ROBERT-MCDOWELL** [comment]
I tried the JS version, does not work on all browsers.

**Comment by bit101** [comment]
> I tried the JS version, does not work on all browsers.

Specifics?

**Comment by ROBERT-MCDOWELL** [comment]
mozilla like version 68 for ex.
it would be nice to tell the minimum browser version to use for each

**Comment by bit101** [comment]
Hmmm. Firefox is the main browser I use. Firefox 68 is two years old. But I tested it via BrowserStack on both Windows and Mac and things seem fine for me.

**Pull request merged**
